# Import Libs

In [236]:
import numpy as np
import pandas as pd

# Pre-processing

In [238]:
job_postings_data = pd.read_csv("postings.csv")
job_postings_data

,job_id,company_name,title,description,max_salary,pay_period,location,company_id,views,med_salary,...,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,NaN,...,Requirements: \n\nWe are seeking a College or ...,1.713398e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0,34021.0
1,1829192,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...",50.0,HOURLY,"Fort Collins, CO",NaN,1.0,NaN,...,NaN,1.712858e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,83200.0,80521.0,8069.0
2,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,NaN,...,We are currently accepting resumes for FOH - A...,1.713278e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0,39061.0
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,NaN,...,This position requires a baseline understandin...,1.712896e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,11040.0,36059.0
4,35982263,NaN,Service Technician,Looking for HVAC service tech with experience ...,80000.0,YEARLY,"Burlington, IA",NaN,3.0,NaN,...,NaN,1.713452e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,70000.0,52601.0,19057.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123844,3906267117,Lozano Smith,Title IX/Investigations Attorney,Our Walnut Creek office is currently seeking a...,195000.0,YEARLY,"Walnut Creek, CA",56120.0,1.0,NaN,...,NaN,1.713571e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,94595.0,6013.0
123845,3906267126,Pinterest,"Staff Software Engineer, ML Serving Platform",About Pinterest:\n\nMillions of people across ...,NaN,NaN,United States,1124131.0,3.0,NaN,...,NaN,1.713572e+12,www.pinterestcareers.com,0,FULL_TIME,NaN,NaN,NaN,NaN,NaN
123846,3906267131,EPS Learning,"Account Executive, Oregon/Washington",Company Overview\n\nEPS Learning is a leading ...,NaN,NaN,"Spokane, WA",90552133.0,3.0,NaN,...,NaN,1.713572e+12,epsoperations.bamboohr.com,0,FULL_TIME,NaN,NaN,NaN,99201.0,53063.0
123847,3906267195,Trelleborg Applied Technologies,Business Development Manager,The Business Development Manager is a 'hunter'...,NaN,NaN,"Texas, United States",2793699.0,4.0,NaN,...,NaN,1.713573e+12,NaN,0,FULL_TIME,NaN,NaN,NaN,NaN,NaN
123848,3906267224,Solugenix,Marketing Social Media Specialist,Marketing Social Media Specialist - $70k – $75...,75000.0,YEARLY,"San Juan Capistrano, CA",43325.0,2.0,NaN,...,NaN,1.713573e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,72500.0,92675.0,6059.0

## Kiểm tra duplicate hay null ở job_id

In [240]:
duplicates = job_postings_data['job_id'].duplicated()
num_duplicates = duplicates.sum()
num_duplicates

0

In [241]:
job_postings_data['job_id'].isnull().sum()

0

# Merge vào bảng benifits và loại bỏ cột inffered vì không sử dụng

In [243]:
job_benefits_data = pd.read_csv("jobs/benefits.csv")
job_benefits_data = job_benefits_data.drop('inferred', axis=1)
job_benefits_data = job_benefits_data.groupby('job_id')['type'].agg(lambda x: ', '.join(x)).reset_index()

In [244]:
job_postings_data = job_postings_data.merge(job_benefits_data, on="job_id", how="left")
job_postings_data

,job_id,company_name,title,description,max_salary,pay_period,location,company_id,views,med_salary,...,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips,type
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,NaN,...,1.713398e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0,34021.0,NaN
1,1829192,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...",50.0,HOURLY,"Fort Collins, CO",NaN,1.0,NaN,...,1.712858e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,83200.0,80521.0,8069.0,NaN
2,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,NaN,...,1.713278e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0,39061.0,NaN
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,NaN,...,1.712896e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,11040.0,36059.0,401(k)
4,35982263,NaN,Service Technician,Looking for HVAC service tech with experience ...,80000.0,YEARLY,"Burlington, IA",NaN,3.0,NaN,...,1.713452e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,70000.0,52601.0,19057.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123844,3906267117,Lozano Smith,Title IX/Investigations Attorney,Our Walnut Creek office is currently seeking a...,195000.0,YEARLY,"Walnut Creek, CA",56120.0,1.0,NaN,...,1.713571e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,94595.0,6013.0,"Medical insurance, Vision insurance, Dental in..."
123845,3906267126,Pinterest,"Staff Software Engineer, ML Serving Platform",About Pinterest:\n\nMillions of people across ...,NaN,NaN,United States,1124131.0,3.0,NaN,...,1.713572e+12,www.pinterestcareers.com,0,FULL_TIME,NaN,NaN,NaN,NaN,NaN,NaN
123846,3906267131,EPS Learning,"Account Executive, Oregon/Washington",Company Overview\n\nEPS Learning is a leading ...,NaN,NaN,"Spokane, WA",90552133.0,3.0,NaN,...,1.713572e+12,epsoperations.bamboohr.com,0,FULL_TIME,NaN,NaN,NaN,99201.0,53063.0,NaN
123847,3906267195,Trelleborg Applied Technologies,Business Development Manager,The Business Development Manager is a 'hunter'...,NaN,NaN,"Texas, United States",2793699.0,4.0,NaN,...,1.713573e+12,NaN,0,FULL_TIME,NaN,NaN,NaN,NaN,NaN,NaN
123848,3906267224,Solugenix,Marketing Social Media Specialist,Marketing Social Media Specialist - $70k – $75...,75000.0,YEARLY,"San Juan Capistrano, CA",43325.0,2.0,NaN,...,1.713573e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,72500.0,92675.0,6059.0,NaN

# Tương tự merge bảng job_skills vào

In [246]:
job_skills_data = pd.read_csv("jobs/job_skills.csv")
job_skills_data = job_skills_data.groupby('job_id')['skill_abr'].agg(lambda x: ', '.join(x)).reset_index() 

job_postings_data = job_postings_data.merge(job_skills_data, on="job_id", how="left")
job_postings_data

,job_id,company_name,title,description,max_salary,pay_period,location,company_id,views,med_salary,...,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips,type,skill_abr
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,NaN,...,NaN,0,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0,34021.0,NaN,"MRKT, SALE"
1,1829192,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...",50.0,HOURLY,"Fort Collins, CO",NaN,1.0,NaN,...,NaN,0,FULL_TIME,USD,BASE_SALARY,83200.0,80521.0,8069.0,NaN,HCPR
2,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,NaN,...,NaN,0,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0,39061.0,NaN,"MGMT, MNFC"
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,NaN,...,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,11040.0,36059.0,401(k),OTHR
4,35982263,NaN,Service Technician,Looking for HVAC service tech with experience ...,80000.0,YEARLY,"Burlington, IA",NaN,3.0,NaN,...,NaN,0,FULL_TIME,USD,BASE_SALARY,70000.0,52601.0,19057.0,NaN,IT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123844,3906267117,Lozano Smith,Title IX/Investigations Attorney,Our Walnut Creek office is currently seeking a...,195000.0,YEARLY,"Walnut Creek, CA",56120.0,1.0,NaN,...,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,94595.0,6013.0,"Medical insurance, Vision insurance, Dental in...","LGL, BD"
123845,3906267126,Pinterest,"Staff Software Engineer, ML Serving Platform",About Pinterest:\n\nMillions of people across ...,NaN,NaN,United States,1124131.0,3.0,NaN,...,www.pinterestcareers.com,0,FULL_TIME,NaN,NaN,NaN,NaN,NaN,NaN,"ENG, IT"
123846,3906267131,EPS Learning,"Account Executive, Oregon/Washington",Company Overview\n\nEPS Learning is a leading ...,NaN,NaN,"Spokane, WA",90552133.0,3.0,NaN,...,epsoperations.bamboohr.com,0,FULL_TIME,NaN,NaN,NaN,99201.0,53063.0,NaN,"SALE, BD"
123847,3906267195,Trelleborg Applied Technologies,Business Development Manager,The Business Development Manager is a 'hunter'...,NaN,NaN,"Texas, United States",2793699.0,4.0,NaN,...,NaN,0,FULL_TIME,NaN,NaN,NaN,NaN,NaN,NaN,"BD, SALE"
123848,3906267224,Solugenix,Marketing Social Media Specialist,Marketing Social Media Specialist - $70k – $75...,75000.0,YEARLY,"San Juan Capistrano, CA",43325.0,2.0,NaN,...,NaN,0,FULL_TIME,USD,BASE_SALARY,72500.0,92675.0,6059.0,NaN,MRKT

# Đã xử lý xong về Job, bây giờ chuyển sang xử lý Company

In [248]:
company_data = pd.read_csv("companies/companies.csv")

company_industries_data = pd.read_csv("companies/company_industries.csv")
company_industries_data = company_industries_data.groupby('company_id')['industry'].agg(lambda x: ', '.join(x)).reset_index()

company_specialities_data = pd.read_csv("companies/company_specialities.csv")
company_specialities_data = company_specialities_data.groupby('company_id')['speciality'].agg(lambda x: ', '.join(x)).reset_index()

employee_counts_data = pd.read_csv("companies/employee_counts.csv")
employee_counts_data = employee_counts_data.groupby('company_id')['time_recorded'].max().reset_index()

company_data = company_data.merge(company_industries_data, on="company_id", how="left")
company_data = company_data.merge(company_specialities_data, on="company_id", how="left")
company_data = company_data.merge(employee_counts_data, on="company_id", how="left")
company_data

,company_id,name,description,company_size,state,country,city,zip_code,address,url,industry,speciality,time_recorded
0,1009,IBM,"At IBM, we do more than work. We create. We cr...",7.0,NY,US,"Armonk, New York",10504,International Business Machines Corp.,https://www.linkedin.com/company/ibm,IT Services and IT Consulting,"Cloud, Mobile, Cognitive, Security, Research, ...",1713501255
1,1016,GE HealthCare,Every day millions of people feel the impact o...,7.0,0,US,Chicago,0,-,https://www.linkedin.com/company/gehealthcare,Hospitals and Health Care,"Healthcare, Biotechnology",1713569031
2,1025,Hewlett Packard Enterprise,Official LinkedIn of Hewlett Packard Enterpris...,7.0,Texas,US,Houston,77389,1701 E Mossy Oaks Rd Spring,https://www.linkedin.com/company/hewlett-packa...,IT Services and IT Consulting,NaN,1713453258
3,1028,Oracle,We’re a cloud technology company that provides...,7.0,Texas,US,Austin,78741,2300 Oracle Way,https://www.linkedin.com/company/oracle,IT Services and IT Consulting,"enterprise, software, applications, database, ...",1713540073
4,1033,Accenture,Accenture is a leading global professional ser...,7.0,0,IE,Dublin 2,0,Grand Canal Harbour,https://www.linkedin.com/company/accenture,Business Consulting and Services,"Management Consulting, Systems Integration and...",1713569451
...,...,...,...,...,...,...,...,...,...,...,...,...,...
24468,103463217,JRC Services,NaN,2.0,0,0,0,0,0,https://www.linkedin.com/company/jrcservices,Facilities Services,NaN,1713552037
24469,103466352,Centent Consulting LLC,Centent Consulting LLC is a reputable human re...,NaN,0,0,0,0,0,https://www.linkedin.com/company/centent-consu...,Business Consulting and Services,NaN,1713550651
24470,103467540,"Kings and Queens Productions, LLC",We are a small but mighty collection of thinke...,NaN,0,0,0,0,0,https://www.linkedin.com/company/kings-and-que...,Broadcast Media Production and Distribution,NaN,1713554225
24471,103468936,WebUnite,Our mission at WebUnite is to offer experience...,NaN,Pennsylvania,US,Southampton,18966,720 2nd Street Pike,https://www.linkedin.com/company/webunite,Business Consulting and Services,NaN,1713535939
24472,103472979,BlackVe,NaN,1.0,0,0,0,0,0,https://www.linkedin.com/company/blackve,Defense and Space Manufacturing,NaN,1713539379

# Tiếp tục merge với Job Postings và Company. Ta sẽ có data về công ty đăng bài trên linkedln

In [250]:
merged_data = job_postings_data.merge(company_data, on="company_id", how="left")
merged_data

,job_id,company_name,title,description_x,max_salary,pay_period,location,company_id,views,med_salary,...,company_size,state,country,city,zip_code_y,address,url,industry,speciality,time_recorded
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,NaN,...,2.0,NJ,US,Jersey City,07302,242 Tenth Street,https://www.linkedin.com/company/corcoran-sawy...,Real Estate,"real estate, new development",1.713409e+09
1,1829192,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...",50.0,HOURLY,"Fort Collins, CO",NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,NaN,...,1.0,Ohio,US,Mariemont,45227,6880 Wooster Pike,https://www.linkedin.com/company/the-national-...,Restaurants,NaN,1.713279e+09
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,NaN,...,2.0,New York,US,Lake Success,11042,3 Dakota Drive,https://www.linkedin.com/company/abrams-fenste...,Law Practice,"Civil Litigation, Corporate & Securities Law, ...",1.712897e+09
4,35982263,NaN,Service Technician,Looking for HVAC service tech with experience ...,80000.0,YEARLY,"Burlington, IA",NaN,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123844,3906267117,Lozano Smith,Title IX/Investigations Attorney,Our Walnut Creek office is currently seeking a...,195000.0,YEARLY,"Walnut Creek, CA",56120.0,1.0,NaN,...,2.0,California,US,Fresno,93720,7404 N Spalding Ave,https://www.linkedin.com/company/lozano-smith,Law Practice,"Education Law, Public Agency Law, Special Educ...",1.713570e+09
123845,3906267126,Pinterest,"Staff Software Engineer, ML Serving Platform",About Pinterest:\n\nMillions of people across ...,NaN,NaN,United States,1124131.0,3.0,NaN,...,5.0,California,US,San Francisco,0,505 Brannan St,https://www.linkedin.com/company/pinterest,Software Development,NaN,1.713572e+09
123846,3906267131,EPS Learning,"Account Executive, Oregon/Washington",Company Overview\n\nEPS Learning is a leading ...,NaN,NaN,"Spokane, WA",90552133.0,3.0,NaN,...,2.0,MD,US,Bethesda,20814,4800 Hampden Ln,https://www.linkedin.com/company/epslearning,Education Administration Programs,NaN,1.713572e+09
123847,3906267195,Trelleborg Applied Technologies,Business Development Manager,The Business Development Manager is a 'hunter'...,NaN,NaN,"Texas, United States",2793699.0,4.0,NaN,...,2.0,Lancashire,GB,Rochdale,OL11 1TQ,Eagle Way,https://www.linkedin.com/company/trelleborg-ap...,Industrial Machinery Manufacturing,"Energy Control Materials, Embedded Rail System...",1.713573e+09
123848,3906267224,Solugenix,Marketing Social Media Specialist,Marketing Social Media Specialist - $70k – $75...,75000.0,YEARLY,"San Juan Capistrano, CA",43325.0,2.0,NaN,...,5.0,California,US,Brea,92823,601 Valencia Ave,https://www.linkedin.com/company/solugenix,IT Services and IT Consulting,"Application Lifecycle Management Services, Sup...",1.713557e+09

In [251]:
merged_data.isnull().sum()

job_id                             0
company_name                    1719
title                              0
description_x                      7
max_salary                     94056
pay_period                     87776
location                           0
company_id                      1717
views                           1689
med_salary                    117569
min_salary                     94056
formatted_work_type                0
applies                       100529
original_listed_time               0
remote_allowed                108603
job_posting_url                    0
application_url                36665
application_type                   0
expiry                             0
closed_time                   122776
formatted_experience_level     29409
skills_desc                   121410
listed_time                        0
posting_domain                 39968
sponsored                          0
work_type                          0
currency                       87776
compensation_type              87776
normalized_salary              87776
zip_code_x                     20872
fips                           27415
type                           95114
skill_abr                       1753
name                            1719
description_y                   2762
company_size                    6707
state                           1757
country                         1718
city                            1720
zip_code_y                      1983
address                         1769
url                             1718
industry                        1875
speciality                     27843
time_recorded                   1718
dtype: int64

# Loại bỏ các cột, để lại các cột để phân tích và đổi tên cột cho dễ đọc hiểu

In [253]:
choosen_column = [
    'job_id',
    'company_name',
    'title',
    'max_salary',
    'pay_period',
    'location',
    'company_id',
    'views',
    'med_salary',
    'min_salary',
    'formatted_work_type',
    'applies',
    'original_listed_time',
    'remote_allowed',
    'application_type',
    'expiry',
    'skill_abr',
    'company_size',
    'state',
    'city',
    'industry',
    'speciality',
    'time_recorded'
]
merged_data = merged_data[choosen_column]
merged_data

,job_id,company_name,title,max_salary,pay_period,location,company_id,views,med_salary,min_salary,...,remote_allowed,application_type,expiry,skill_abr,company_size,state,city,industry,speciality,time_recorded
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,NaN,17.0,...,NaN,ComplexOnsiteApply,1.715990e+12,"MRKT, SALE",2.0,NJ,Jersey City,Real Estate,"real estate, new development",1.713409e+09
1,1829192,NaN,Mental Health Therapist/Counselor,50.0,HOURLY,"Fort Collins, CO",NaN,1.0,NaN,30.0,...,NaN,ComplexOnsiteApply,1.715450e+12,HCPR,NaN,NaN,NaN,NaN,NaN,NaN
2,10998357,The National Exemplar,Assitant Restaurant Manager,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,NaN,45000.0,...,NaN,ComplexOnsiteApply,1.715870e+12,"MGMT, MNFC",1.0,Ohio,Mariemont,Restaurants,NaN,1.713279e+09
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,NaN,140000.0,...,NaN,ComplexOnsiteApply,1.715488e+12,OTHR,2.0,New York,Lake Success,Law Practice,"Civil Litigation, Corporate & Securities Law, ...",1.712897e+09
4,35982263,NaN,Service Technician,80000.0,YEARLY,"Burlington, IA",NaN,3.0,NaN,60000.0,...,NaN,ComplexOnsiteApply,1.716044e+12,IT,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123844,3906267117,Lozano Smith,Title IX/Investigations Attorney,195000.0,YEARLY,"Walnut Creek, CA",56120.0,1.0,NaN,120000.0,...,NaN,ComplexOnsiteApply,1.716163e+12,"LGL, BD",2.0,California,Fresno,Law Practice,"Education Law, Public Agency Law, Special Educ...",1.713570e+09
123845,3906267126,Pinterest,"Staff Software Engineer, ML Serving Platform",NaN,NaN,United States,1124131.0,3.0,NaN,NaN,...,1.0,OffsiteApply,1.716164e+12,"ENG, IT",5.0,California,San Francisco,Software Development,NaN,1.713572e+09
123846,3906267131,EPS Learning,"Account Executive, Oregon/Washington",NaN,NaN,"Spokane, WA",90552133.0,3.0,NaN,NaN,...,1.0,OffsiteApply,1.716164e+12,"SALE, BD",2.0,MD,Bethesda,Education Administration Programs,NaN,1.713572e+09
123847,3906267195,Trelleborg Applied Technologies,Business Development Manager,NaN,NaN,"Texas, United States",2793699.0,4.0,NaN,NaN,...,1.0,ComplexOnsiteApply,1.716165e+12,"BD, SALE",2.0,Lancashire,Rochdale,Industrial Machinery Manufacturing,"Energy Control Materials, Embedded Rail System...",1.713573e+09
123848,3906267224,Solugenix,Marketing Social Media Specialist,75000.0,YEARLY,"San Juan Capistrano, CA",43325.0,2.0,NaN,70000.0,...,NaN,ComplexOnsiteApply,1.716165e+12,MRKT,5.0,California,Brea,IT Services and IT Consulting,"Application Lifecycle Management Services, Sup...",1.713557e+09

# Bỏ các hàng nơi mà có company_name và speciality là NaN hoặc null

In [255]:
pretty_column_name = {'title': 'job_title','formatted_work_type': 'work_type','original_listed_time': 'listed_time'}
data = merged_data.rename(columns=pretty_column_name)
data.dropna(subset=['company_name', 'speciality'], inplace=True)
data

,job_id,company_name,job_title,max_salary,pay_period,location,company_id,views,med_salary,min_salary,...,remote_allowed,application_type,expiry,skill_abr,company_size,state,city,industry,speciality,time_recorded
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,NaN,17.0,...,NaN,ComplexOnsiteApply,1.715990e+12,"MRKT, SALE",2.0,NJ,Jersey City,Real Estate,"real estate, new development",1.713409e+09
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,NaN,140000.0,...,NaN,ComplexOnsiteApply,1.715488e+12,OTHR,2.0,New York,Lake Success,Law Practice,"Civil Litigation, Corporate & Securities Law, ...",1.712897e+09
5,91700727,Downtown Raleigh Alliance,Economic Development and Planning Intern,20.0,HOURLY,"Raleigh, NC",1481176.0,9.0,NaN,14.0,...,NaN,ComplexOnsiteApply,1.716048e+12,PRJM,1.0,North Carolina,Raleigh,Non-profit Organizations,"Economic Development, Clean & Safe Ambassodors...",1.713460e+09
8,1218575,Children's Nebraska,Respiratory Therapist,NaN,NaN,"Omaha, NE",721189.0,3.0,NaN,NaN,...,NaN,OffsiteApply,1.714940e+12,HCPR,5.0,NE,Omaha,Hospitals and Health Care,"Neonatology, Fetal Medicine, Cardiology, Heart...",1.713479e+09
9,2264355,Bay West Church,Worship Leader,NaN,MONTHLY,"Palm Bay, FL",28631247.0,5.0,350.0,NaN,...,NaN,ComplexOnsiteApply,1.715048e+12,"DSGN, ART, IT",NaN,Florida,Melbourne,Religious Institutions,"Biblical preaching, Worship services, Discipli...",1.712459e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123841,3906266217,The Dyrt,Senior Frontend/App Developer,NaN,NaN,United States,6404239.0,1.0,NaN,NaN,...,1.0,OffsiteApply,1.716163e+12,"IT, ENG",1.0,OR,Portland,Software Development,"Camping, Campground Reviews, Campground Photos...",1.713571e+09
123843,3906266272,"TalentBurst, an Inc 5000 company",Quality Engineer,50.0,HOURLY,"Irvine, CA",122451.0,1.0,NaN,30.0,...,NaN,ComplexOnsiteApply,1.716164e+12,ENG,5.0,MA,Natick,Staffing and Recruiting,"IT staffing, MSP, VMS staffing, Accounting and...",1.713552e+09
123844,3906267117,Lozano Smith,Title IX/Investigations Attorney,195000.0,YEARLY,"Walnut Creek, CA",56120.0,1.0,NaN,120000.0,...,NaN,ComplexOnsiteApply,1.716163e+12,"LGL, BD",2.0,California,Fresno,Law Practice,"Education Law, Public Agency Law, Special Educ...",1.713570e+09
123847,3906267195,Trelleborg Applied Technologies,Business Development Manager,NaN,NaN,"Texas, United States",2793699.0,4.0,NaN,NaN,...,1.0,ComplexOnsiteApply,1.716165e+12,"BD, SALE",2.0,Lancashire,Rochdale,Industrial Machinery Manufacturing,"Energy Control Materials, Embedded Rail System...",1.713573e+09
123848,3906267224,Solugenix,Marketing Social Media Specialist,75000.0,YEARLY,"San Juan Capistrano, CA",43325.0,2.0,NaN,70000.0,...,NaN,ComplexOnsiteApply,1.716165e+12,MRKT,5.0,California,Brea,IT Services and IT Consulting,"Application Lifecycle Management Services, Sup...",1.713557e+09

# Điền vào các chỗ có giá trị NaN ở cột med_salary, min_salary, max_salary với giá trị điền vào là giá trị trung bình của cột med_salary, min_salary, max_salary

In [257]:
data['med_salary'] = data['med_salary'].fillna(data['med_salary'].mean())
data['min_salary'] = data['min_salary'].fillna(data['min_salary'].mean())
data['max_salary'] = data['max_salary'].fillna(data['max_salary'].mean())
data

,job_id,company_name,job_title,max_salary,pay_period,location,company_id,views,med_salary,min_salary,...,remote_allowed,application_type,expiry,skill_abr,company_size,state,city,industry,speciality,time_recorded
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,20.000000,HOURLY,"Princeton, NJ",2774458.0,20.0,22743.304532,17.000000,...,NaN,ComplexOnsiteApply,1.715990e+12,"MRKT, SALE",2.0,NJ,Jersey City,Real Estate,"real estate, new development",1.713409e+09
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,175000.000000,YEARLY,"New Hyde Park, NY",766262.0,16.0,22743.304532,140000.000000,...,NaN,ComplexOnsiteApply,1.715488e+12,OTHR,2.0,New York,Lake Success,Law Practice,"Civil Litigation, Corporate & Securities Law, ...",1.712897e+09
5,91700727,Downtown Raleigh Alliance,Economic Development and Planning Intern,20.000000,HOURLY,"Raleigh, NC",1481176.0,9.0,22743.304532,14.000000,...,NaN,ComplexOnsiteApply,1.716048e+12,PRJM,1.0,North Carolina,Raleigh,Non-profit Organizations,"Economic Development, Clean & Safe Ambassodors...",1.713460e+09
8,1218575,Children's Nebraska,Respiratory Therapist,92745.101314,NaN,"Omaha, NE",721189.0,3.0,22743.304532,65506.116111,...,NaN,OffsiteApply,1.714940e+12,HCPR,5.0,NE,Omaha,Hospitals and Health Care,"Neonatology, Fetal Medicine, Cardiology, Heart...",1.713479e+09
9,2264355,Bay West Church,Worship Leader,92745.101314,MONTHLY,"Palm Bay, FL",28631247.0,5.0,350.000000,65506.116111,...,NaN,ComplexOnsiteApply,1.715048e+12,"DSGN, ART, IT",NaN,Florida,Melbourne,Religious Institutions,"Biblical preaching, Worship services, Discipli...",1.712459e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123841,3906266217,The Dyrt,Senior Frontend/App Developer,92745.101314,NaN,United States,6404239.0,1.0,22743.304532,65506.116111,...,1.0,OffsiteApply,1.716163e+12,"IT, ENG",1.0,OR,Portland,Software Development,"Camping, Campground Reviews, Campground Photos...",1.713571e+09
123843,3906266272,"TalentBurst, an Inc 5000 company",Quality Engineer,50.000000,HOURLY,"Irvine, CA",122451.0,1.0,22743.304532,30.000000,...,NaN,ComplexOnsiteApply,1.716164e+12,ENG,5.0,MA,Natick,Staffing and Recruiting,"IT staffing, MSP, VMS staffing, Accounting and...",1.713552e+09
123844,3906267117,Lozano Smith,Title IX/Investigations Attorney,195000.000000,YEARLY,"Walnut Creek, CA",56120.0,1.0,22743.304532,120000.000000,...,NaN,ComplexOnsiteApply,1.716163e+12,"LGL, BD",2.0,California,Fresno,Law Practice,"Education Law, Public Agency Law, Special Educ...",1.713570e+09
123847,3906267195,Trelleborg Applied Technologies,Business Development Manager,92745.101314,NaN,"Texas, United States",2793699.0,4.0,22743.304532,65506.116111,...,1.0,ComplexOnsiteApply,1.716165e+12,"BD, SALE",2.0,Lancashire,Rochdale,Industrial Machinery Manufacturing,"Energy Control Materials, Embedded Rail System...",1.713573e+09
123848,3906267224,Solugenix,Marketing Social Media Specialist,75000.000000,YEARLY,"San Juan Capistrano, CA",43325.0,2.0,22743.304532,70000.000000,...,NaN,ComplexOnsiteApply,1.716165e+12,MRKT,5.0,California,Brea,IT Services and IT Consulting,"Application Lifecycle Management Services, Sup...",1.713557e+09

# Chuyển đổi UNIX TIME sang kiểu mm/dd/yyyy

In [259]:
data['time_recorded'] = pd.to_datetime(data['time_recorded'], unit='s', errors='coerce').dt.strftime('%m/%d/%Y')

# Kiểm tra kết quả
print(data['time_recorded'].head(10))

0     04/18/2024
3     04/12/2024
5     04/18/2024
8     04/18/2024
9     04/07/2024
10    04/15/2024
11    04/11/2024
14    04/19/2024
15    04/18/2024
19    04/16/2024
Name: time_recorded, dtype: object

# Điền vào chỗ còn trống của các cột pay_period, applies, remote_allowed, company_size, views với giá trị lần lượt là 'MONTHLY', 0, 0, 0, 0

In [261]:
data['pay_period'] = data['pay_period'].fillna('MONTHLY')
data['applies'] = data['applies'].fillna(0)
data['remote_allowed'] = data['remote_allowed'].fillna(0)
data['company_size'] = data['company_size'].fillna(0)
data['views'] = data['views'].fillna(0)
data

,job_id,company_name,job_title,max_salary,pay_period,location,company_id,views,med_salary,min_salary,...,remote_allowed,application_type,expiry,skill_abr,company_size,state,city,industry,speciality,time_recorded
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,20.000000,HOURLY,"Princeton, NJ",2774458.0,20.0,22743.304532,17.000000,...,0.0,ComplexOnsiteApply,1.715990e+12,"MRKT, SALE",2.0,NJ,Jersey City,Real Estate,"real estate, new development",04/18/2024
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,175000.000000,YEARLY,"New Hyde Park, NY",766262.0,16.0,22743.304532,140000.000000,...,0.0,ComplexOnsiteApply,1.715488e+12,OTHR,2.0,New York,Lake Success,Law Practice,"Civil Litigation, Corporate & Securities Law, ...",04/12/2024
5,91700727,Downtown Raleigh Alliance,Economic Development and Planning Intern,20.000000,HOURLY,"Raleigh, NC",1481176.0,9.0,22743.304532,14.000000,...,0.0,ComplexOnsiteApply,1.716048e+12,PRJM,1.0,North Carolina,Raleigh,Non-profit Organizations,"Economic Development, Clean & Safe Ambassodors...",04/18/2024
8,1218575,Children's Nebraska,Respiratory Therapist,92745.101314,MONTHLY,"Omaha, NE",721189.0,3.0,22743.304532,65506.116111,...,0.0,OffsiteApply,1.714940e+12,HCPR,5.0,NE,Omaha,Hospitals and Health Care,"Neonatology, Fetal Medicine, Cardiology, Heart...",04/18/2024
9,2264355,Bay West Church,Worship Leader,92745.101314,MONTHLY,"Palm Bay, FL",28631247.0,5.0,350.000000,65506.116111,...,0.0,ComplexOnsiteApply,1.715048e+12,"DSGN, ART, IT",0.0,Florida,Melbourne,Religious Institutions,"Biblical preaching, Worship services, Discipli...",04/07/2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123841,3906266217,The Dyrt,Senior Frontend/App Developer,92745.101314,MONTHLY,United States,6404239.0,1.0,22743.304532,65506.116111,...,1.0,OffsiteApply,1.716163e+12,"IT, ENG",1.0,OR,Portland,Software Development,"Camping, Campground Reviews, Campground Photos...",04/20/2024
123843,3906266272,"TalentBurst, an Inc 5000 company",Quality Engineer,50.000000,HOURLY,"Irvine, CA",122451.0,1.0,22743.304532,30.000000,...,0.0,ComplexOnsiteApply,1.716164e+12,ENG,5.0,MA,Natick,Staffing and Recruiting,"IT staffing, MSP, VMS staffing, Accounting and...",04/19/2024
123844,3906267117,Lozano Smith,Title IX/Investigations Attorney,195000.000000,YEARLY,"Walnut Creek, CA",56120.0,1.0,22743.304532,120000.000000,...,0.0,ComplexOnsiteApply,1.716163e+12,"LGL, BD",2.0,California,Fresno,Law Practice,"Education Law, Public Agency Law, Special Educ...",04/19/2024
123847,3906267195,Trelleborg Applied Technologies,Business Development Manager,92745.101314,MONTHLY,"Texas, United States",2793699.0,4.0,22743.304532,65506.116111,...,1.0,ComplexOnsiteApply,1.716165e+12,"BD, SALE",2.0,Lancashire,Rochdale,Industrial Machinery Manufacturing,"Energy Control Materials, Embedded Rail System...",04/20/2024
123848,3906267224,Solugenix,Marketing Social Media Specialist,75000.000000,YEARLY,"San Juan Capistrano, CA",43325.0,2.0,22743.304532,70000.000000,...,0.0,ComplexOnsiteApply,1.716165e+12,MRKT,5.0,California,Brea,IT Services and IT Consulting,"Application Lifecycle Management Services, Sup...",04/19/2024

In [262]:
try:
    data.to_csv("cleaned-data.csv", index=False)
except Exception as e:
    print(f"An error occurred: {e}")